cookie:
  expiry_days: 10
  key: some_signature_key
  name: auto_report
credentials:
  usernames:
    jd94:
      email: johndoe@gmail.com
      name: John Doe
      password:
      - $2b$12$kDq8PkYUIDT1cAMDwblkEeZbknxzwmSnBJjx6IwwvH86r3CApE8AK
    princess_doe:
      email: jj@gmail.com
      name: Jane Doe
      password:
      - $2b$12$kQUzqlkxo0Ve8i4eSLyFdeK6578iTTuEpFpEhXD2HLR74ztrqcfQ.
preauthorized:
  emails:
  - autoreport@gmail.com
